package data;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class Database {
    private static Database theInstance;
    private Connection cnx;

    // Cambia estos valores según tu instalación de MySQL
    private final String SERVER = "localhost";
    private final String PORT = "3306";
    private final String DATABASE = "HospitalProy";
    private final String USER = "root";
    private final String PASSWORD = "1234"; // Cambia por tu contraseña

    private Database() {
        cnx = getConnection();
    }

    public static Database instance() {
        if (theInstance == null) {
            theInstance = new Database();
        }
        return theInstance;
    }

    private Connection getConnection() {
        try {
            String URL_conexion = "jdbc:mysql://" + SERVER + ":" + PORT + "/" +
                    DATABASE + "?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC";
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            return DriverManager.getConnection(URL_conexion, USER, PASSWORD);
        } catch (Exception e) {
            throw new RuntimeException("Error al conectar con la base de datos: " + e.getMessage(), e);
        }
    }

    public PreparedStatement prepareStatement(String statement) throws SQLException {
        if (cnx == null || cnx.isClosed()) {
            cnx = getConnection();
        }
        return cnx.prepareStatement(statement);
    }

    public int executeUpdate(PreparedStatement statement) throws SQLException {
        try {
            return statement.executeUpdate();
        } catch (SQLException ex) {
            throw new SQLException("Error en executeUpdate: " + ex.getMessage(), ex);
        }
    }
    public PreparedStatement prepareStatement(String statement, int autoGeneratedKeys) throws SQLException {
        if (cnx == null || cnx.isClosed()) {
            cnx = getConnection();
        }
        return cnx.prepareStatement(statement, autoGeneratedKeys);
    }

    public ResultSet executeQuery(PreparedStatement statement) throws SQLException {
        try {
            return statement.executeQuery();
        } catch (SQLException ex) {
            throw new SQLException("Error en executeQuery: " + ex.getMessage(), ex);
        }
    }

    public void close() {
        try {
            if (cnx != null && !cnx.isClosed()) {
                cnx.close();
                cnx = null; // Ayuda a liberar recursos
            }
        } catch (SQLException e) {
            System.err.println("Error cerrando la conexión: " + e.getMessage());
        }
    }
}